[tool.poetry]
name = "wikidspark"
version = "0.1.0"
description = ""
authors = ["Kristian Zarebski <krizar312@gmail.com>"]
include = ['README.md', 'LICENSE', 'wikidspark/wikidata/properties.json']
exclude = ['wikidspark/wikidata/_upload.py']

[tool.poetry.dependencies]
python ="^3.8,<4.0"
wikipedia = "^1.4.0"
tqdm = "^4.48.2"
pandas = "^1.4.1"
urllib3 = "^1.26.9"
click = "^8.1.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
