[tool.poetry]
name = "wikidspark"
version = "0.1.0"
description = ""
authors = ["Kristian Zarebski <krizar312@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6.1"
wikipedia = "^1.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
