name: Deploy to PyPi
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build Wheels and Package 🛠️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Build Module
        run: poetry build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          if-no-files-found: error
          name: python-package-distributions
          path: dist/
  publish_test:
    name: Publish to TestPyPi 🧪
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/wikidspark
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to TestPyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
  publish:
    name: Publish to PyPi 🐍📦
    needs:
      - publish_test
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/wikidspark
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
  github-release:
    name: Create Signed GitHub Release 🔏
    needs:
      - publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          LATESTCHANGES=$(awk '
            BEGIN { header_found = 0 }
            /^## / {
                if (header_found == 0) {
                    header = $0
                    header_found = 1
                    next
                } else {
                  exit
                }
            }
            header_found == 1 && /^\* / { print }
          ' CHANGELOG.md)
          gh release create
          '${{ github.ref_name }}'
          --notes "$LATESTCHANGES"
          --title 'Wikidspark ${{ github.ref_name }}'
          --repo '${{ github.repository }}'
      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          '${{ github.ref_name }}' dist/**
          --repo '${{ github.repository }}'