name: WikidSpark

on: [push]

jobs:
    run:
       name: ${{ matrix.os }} ${{ matrix.architecture}} Python v${{ matrix.python }}
       runs-on: ${{ matrix.os }}
       strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python: ["3.11", "3.12", "3.13"]
                architecture: [x64]
       env:
            OS : ${{ matrix.os }}
            ARCHITECTURE: ${{ matrix.architecture }}
            PYTHON : Python ${{ matrix.python }}
       steps:
            - uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                    python-version : ${{ matrix.python }}
                    architecture : ${{ matrix.architecture }}

            - name: Install Python Requirements
              run : |
                    python -m pip install --upgrade pip
                    python -m pip install --user poetry pytest-cov codecov pyYAML

            - name: Install Package
              run : python -m poetry install

            - name: Run Tests
              run : |
                    poetry run pip install -y pytest-cov
                    poetry run pytest --cov=./ --cov-report=xml

            - name: Upload Coverage (Ubuntu Python3.13)
              uses: codecov/codecov-action@v5
              with:
                  token : ${{ secrets.CODECOV_TOKEN }}
                  files : ./coverage.xml
                  directory : ./coverage/reports
                  flags : unittests
                  fail_ci_if_error: true
                  env_vars: OS,PYTHON,ARCHITECTURE
                  name : codecov-umbrella
              if: matrix.os == 'ubuntu-latest' && matrix.python == 3.13
