name: WikidSpark

on: [push]

jobs:
    run:
       name: ${{ matrix.os }} ${{ matrix.architecture}} Python v${{ matrix.python }}
       runs-on: ${{ matrix.os }}
       strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest] #, windows-latest]
                python: [3.6, 3.7, 3.8]
                architecture: [x64]
                #include:
                #    - os: windows-latest
                #      architecture: x86
       env:
            OS : ${{ matrix.os }}
            ARCHITECTURE: ${{ matrix.architecture }}
            PYTHON : Python ${{ matrix.python }}
       steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                    python-version : ${{ matrix.python }}
                    architecture : ${{ matrix.architecture }}

            - name: Install Python Requirements
              run : |
                    python -m pip install --upgrade pip
                    python -m pip install --user poetry pytest-cov codecov pyYAML

            - name: Install Package
              run : python -m poetry install

            - name: Run Tests
              run : |
                    python -c "import time; time.sleep(2)"
                    python -m poetry add pytest-cov
                    python -m poetry run pytest --cov=./ --cov-report=xml

            - name: Run Examples
              run:  for i in $(ls examples/*.py); do poetry run python $i; done 

            - name: Upload Coverage (Ubuntu Python3.8)
              uses: codecov/codecov-action@v1
              with:
                  token : ${{secrets.CODECOV_TOKEN}}
                  file : ./coverage.xml
                  directory : ./coverage/reports
                  flags : unittests
                  fail_ci_if_error: true
                  env_vars: OS,PYTHON,ARCHITECTURE
                  name : codecov-umbrella
              if: matrix.os == 'ubuntu-latest' && matrix.python == 3.8
